# -*- coding: utf-8 -*-
"""7.5_Despliegue ataque corazon con streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WK-U1VRaR8o2I-xf7lYUCN_hXJcsplgm

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerias principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-class.pkl'
# The original line caused an AttributeError because min_max_scaler and variables were swapped.
# Correcting the unpacking order:
modelo, abelencoder, variables, min_max_scaler = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
data = pd.read_excel("/content/ataque_corazon.xlsx", sheet_name="Predicciones futuras")
data.head()

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de ataque de corazon')

age = st.slider('age', min_value=14, max_value=100, value=20, step=1)
hypertension = st.selectbox('hypertension', ['Yes', 'No'])
heart_disease = st.selectbox('heart_disease', ['Yes', 'No'])
ever_married = st.selectbox('ever_married', ['Yes', 'No'])
avg_glucose_level = st.number_input('avg_glucose_level', min_value=40.00, max_value=600.00, value=100.0, step=1.00, format="%.1f")
smoking_status = st.selectbox('smoking_status', ["'formely smoked'", "'never smoked'","smokes","Unknown"])


#Dataframe
datos = [[age, hypertension,heart_disease,ever_married,avg_glucose_level, smoking_status]]
data = pd.DataFrame(datos, columns=['age', 'hypertension','heart_disease','ever_married','avg_glucose_level', 'smoking_status']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['hypertension', 'heart_disease','ever_married', 'smoking_status'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

# Se normaliza la edad y el nivel de glucosa para predecir
# En los despliegues no se llama fit, solo transform
# El escalador espera las mismas columnas con las que fue entrenado
data_preparada[['age', 'avg_glucose_level']] = min_max_scaler.transform(data_preparada[['age', 'avg_glucose_level']])
data_preparada.head()

"""# **Predicciones**"""

#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

data['Prediccion']=Y_pred
data.head()

#Predicciones finales
data

# Recordar medida de error del modelo
st.warning("El modelo tiene una precision del 73%%")